""" Ronaldadetes"""

import asyncio

from kannax import Message, kannax

@kannax.on_cmd("cr7", about={"header": "Cristiano Ronaldo"})
async def cr7_(message: Message):
  out_str = f"""
GIOVANYGIOVANYGIOV
GIOVANYGIOVANYGIOVANY
GIOVANY
GIOVANY
GIOVANYGIOVANYGIOVANYGIOVANYGIOVANY
GIOVANY
v
v
v
GIOVANY
vANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANYGIOVANY
    """
  await message.edit(out_str)

